import { Inter } from "next/font/google";
import "../styles/globals.css";

interface Metadata {
  title: string;
  description: string;
}

interface RootLayoutProps {
  children: React.ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "탑개미자원",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html lang="ko">
      <body className={`${inter.className}`}>
        <div />
        {children}
      </body>
    </html>
  );
}
