const data = [
  {
    id: 1,
    isDone: true,
    name: "이원호",
    location: "고양시 후곡마을",
    item: "고철",
    date: "2023/11/17",
  },
  {
    id: 1,
    isDone: true,
    name: "이원호2",
    location: "고양시 후곡마을",
    item: "고철",
    date: "2023/11/17",
  },
  {
    id: 1,
    isDone: true,
    name: "이원호3",
    location: "고양시 후곡마을",
    item: "고철",
    date: "2023/11/17",
  },
  {
    id: 1,
    isDone: true,
    name: "이원호4",
    location: "고양시 후곡마을",
    item: "고철",
    date: "2023/11/17",
  },
  {
    id: 1,
    isDone: true,
    name: "이원호5",
    location: "고양시 후곡마을",
    item: "고철",
    date: "2023/11/17",
  },
  {
    id: 1,
    isDone: false,
    name: "이원호6",
    location: "고양시 후곡마을",
    item: "고철",
    date: "2023/11/17",
  },
  {
    id: 1,
    isDone: true,
    name: "이원호7",
    location: "고양시 후곡마을",
    item: "고철",
    date: "2023/11/17",
  },
  {
    id: 1,
    isDone: false,
    name: "이원호8",
    location: "고양시 후곡마을",
    item: "고철",
    date: "2023/11/17",
  },
  {
    id: 1,
    isDone: false,
    name: "이원호9",
    location: "고양시 후곡마을",
    item: "고철",
    date: "2023/11/17",
  },
];

export default data;
